language: emacs-lisp
sudo: false
env:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=snapshot
matrix:
  allow_failures:
    - env: EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - curl -SOL https://github.com/flycheck/emacs-travis/raw/master/emacs-travis.mk
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
script:
  - make compile
