env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot

before_install:
  - git submodule --quiet update --init --recursive

install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask install

script:
  - cask build

notifications:
  email: false
