language: emacs
cache: apt
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  - fast_finish: true
  - allow_failures:
      - env: EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
install:
  - cask install
script:
  - echo "*** Emacs Version ***"
  - export ECUKES_EMACS=${EMACS:-$(which emacs)}
  - $ECUKES_EMACS --version
  - cask exec buttercup -L .
