language: emacs-lisp

branches:
  only:
    - master

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa

env:
  matrix:
    - EMACS=emacs24        EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
  global:
    - PATH=$HOME/.cask/bin:$PATH

before_install:
  - sudo add-apt-repository -y "$EMACS_PPA"
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes -qq "$EMACS"
  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true # OK to fail
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10 https://raw.github.com/cask/cask/master/go | python
  - cask install
script:
  cask exec ert-runner
