language: emacs-lisp

script:
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask install
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-25.3-travis    
    - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh

notifications:
  email: false
