
# .travis.yml
# build script for travis continuous integration
# --------------------------------------------------------------------------------

# see https://travis-ci.org/bburns/clipmon
# adapted from https://github.com/magnars/dash.el/blob/master/.travis.yml
# and https://github.com/company-mode/company-mode/blob/master/.travis.yml

# the emacs snapshot is from here, and should be the latest version (ie 25.1):
# https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

# validate this file here: http://lint.travis-ci.org/


# travis-lint no longer permits emacs-lisp
language: generic

# test on linux and osx (windows not available on travis ci yet).
# this os key also multiplies the build matrix (set below).
os:
    - linux
    - osx

# build matrix - test on different emacs versions
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs25

install:
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "linux-emacs24" ]]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "linux-emacs25" ]]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get -qq -f install &&
        sudo apt-get install -qq emacs-snapshot;
    fi
  # build from source - per INSTALL instructions [slow]
        # wget http://mirrors.kernel.org/gnu/emacs/emacs-24.5.tar.gz
        # tar xf emacs-24.5.tar.gz
        # cd emacs-24.5
        # .configure --with-ns
  # install with brew [builds from source, took ~15mins]
        # brew install emacs ;
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "osx-emacs24" ]]; then
        wget https://emacsformacosx.com/emacs-builds/Emacs-24.5-universal.dmg &&
        hdiutil attach Emacs-24.5-universal.dmg &&
        sudo ln -s /Volumes/Emacs/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs;
    fi
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "osx-emacs25" ]]; then
        wget https://emacsformacosx.com/emacs-builds/Emacs-25.1-universal.dmg &&
        hdiutil attach Emacs-25.1-universal.dmg &&
        sudo ln -s /Volumes/Emacs/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs;
    fi


script:
  make test

# By default, a build email is sent to the committer and the author,
# but only if they have access to the repository the commit was pushed to.
notifications:
  email:
    on_success: always
    on_failure: always
